package com.bridea.siak.model;

// default package
// Generated Jun 4, 2014 2:32:41 AM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * MAmbil generated by hbm2java
 */
@Entity
@Table(name = "m_ambil", catalog = "siak")
public class MAmbil implements java.io.Serializable {

	private Integer AIdAmbil;
	private MMataKuliah MMataKuliah;
	private MDosen MDosen;
	private MMahasiswa MMahasiswa;
	private String AKelas;
	private String ALahanPraktek;
	private MKomponenNilai MKomponenNilai;

	public MAmbil() {
	}

	public MAmbil(MMataKuliah MMataKuliah, MDosen MDosen,
			MMahasiswa MMahasiswa, String AKelas, String ALahanPraktek) {
		this.MMataKuliah = MMataKuliah;
		this.MDosen = MDosen;
		this.MMahasiswa = MMahasiswa;
		this.AKelas = AKelas;
		this.ALahanPraktek = ALahanPraktek;
	}

	public MAmbil(MMataKuliah MMataKuliah, MDosen MDosen,
			MMahasiswa MMahasiswa, String AKelas, String ALahanPraktek,
			MKomponenNilai MKomponenNilai) {
		this.MMataKuliah = MMataKuliah;
		this.MDosen = MDosen;
		this.MMahasiswa = MMahasiswa;
		this.AKelas = AKelas;
		this.ALahanPraktek = ALahanPraktek;
		this.MKomponenNilai = MKomponenNilai;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "a_id_ambil", unique = true, nullable = false)
	public Integer getAIdAmbil() {
		return this.AIdAmbil;
	}

	public void setAIdAmbil(Integer AIdAmbil) {
		this.AIdAmbil = AIdAmbil;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "a_kode_mk", nullable = false)
	public MMataKuliah getMMataKuliah() {
		return this.MMataKuliah;
	}

	public void setMMataKuliah(MMataKuliah MMataKuliah) {
		this.MMataKuliah = MMataKuliah;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "a_kode_dosen", nullable = false)
	public MDosen getMDosen() {
		return this.MDosen;
	}

	public void setMDosen(MDosen MDosen) {
		this.MDosen = MDosen;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "a_npm", nullable = false)
	public MMahasiswa getMMahasiswa() {
		return this.MMahasiswa;
	}

	public void setMMahasiswa(MMahasiswa MMahasiswa) {
		this.MMahasiswa = MMahasiswa;
	}

	@Column(name = "a_kelas", nullable = false, length = 20)
	public String getAKelas() {
		return this.AKelas;
	}

	public void setAKelas(String AKelas) {
		this.AKelas = AKelas;
	}

	@Column(name = "a_lahan_praktek", nullable = false, length = 65535)
	public String getALahanPraktek() {
		return this.ALahanPraktek;
	}

	public void setALahanPraktek(String ALahanPraktek) {
		this.ALahanPraktek = ALahanPraktek;
	}

	@OneToOne(fetch = FetchType.EAGER, mappedBy = "MAmbil")
	public MKomponenNilai getMKomponenNilai() {
		return this.MKomponenNilai;
	}

	public void setMKomponenNilai(MKomponenNilai MKomponenNilai) {
		this.MKomponenNilai = MKomponenNilai;
	}

}
