package com.bridea.siak.model;

// default package
// Generated Jun 3, 2014 9:42:46 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * MAmbil generated by hbm2java
 */
@Entity
@Table(name = "m_ambil", catalog = "siak")
public class MAmbil implements java.io.Serializable {

	private Integer AIdAmbil;
	private MMataKuliah MMataKuliah;
	private MKomponenNilai MKomponenNilai;
	private MDosen MDosen;
	private String AKelas;
	private String ALahanPraktek;
	private Set<MDetailAmbil> MDetailAmbils = new HashSet<MDetailAmbil>(0);

	public MAmbil() {
	}

	public MAmbil(MMataKuliah MMataKuliah, MKomponenNilai MKomponenNilai,
			MDosen MDosen, String AKelas, String ALahanPraktek) {
		this.MMataKuliah = MMataKuliah;
		this.MKomponenNilai = MKomponenNilai;
		this.MDosen = MDosen;
		this.AKelas = AKelas;
		this.ALahanPraktek = ALahanPraktek;
	}

	public MAmbil(MMataKuliah MMataKuliah, MKomponenNilai MKomponenNilai,
			MDosen MDosen, String AKelas, String ALahanPraktek,
			Set<MDetailAmbil> MDetailAmbils) {
		this.MMataKuliah = MMataKuliah;
		this.MKomponenNilai = MKomponenNilai;
		this.MDosen = MDosen;
		this.AKelas = AKelas;
		this.ALahanPraktek = ALahanPraktek;
		this.MDetailAmbils = MDetailAmbils;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "a_id_ambil", unique = true, nullable = false)
	public Integer getAIdAmbil() {
		return this.AIdAmbil;
	}

	public void setAIdAmbil(Integer AIdAmbil) {
		this.AIdAmbil = AIdAmbil;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "a_kode_mk", nullable = false)
	public MMataKuliah getMMataKuliah() {
		return this.MMataKuliah;
	}

	public void setMMataKuliah(MMataKuliah MMataKuliah) {
		this.MMataKuliah = MMataKuliah;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "a_id_komponen_nilai", nullable = false)
	public MKomponenNilai getMKomponenNilai() {
		return this.MKomponenNilai;
	}

	public void setMKomponenNilai(MKomponenNilai MKomponenNilai) {
		this.MKomponenNilai = MKomponenNilai;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "a_kode_dosen", nullable = false)
	public MDosen getMDosen() {
		return this.MDosen;
	}

	public void setMDosen(MDosen MDosen) {
		this.MDosen = MDosen;
	}

	@Column(name = "a_kelas", nullable = false, length = 20)
	public String getAKelas() {
		return this.AKelas;
	}

	public void setAKelas(String AKelas) {
		this.AKelas = AKelas;
	}

	@Column(name = "a_lahan_praktek", nullable = false, length = 65535)
	public String getALahanPraktek() {
		return this.ALahanPraktek;
	}

	public void setALahanPraktek(String ALahanPraktek) {
		this.ALahanPraktek = ALahanPraktek;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "MAmbil")
	public Set<MDetailAmbil> getMDetailAmbils() {
		return this.MDetailAmbils;
	}

	public void setMDetailAmbils(Set<MDetailAmbil> MDetailAmbils) {
		this.MDetailAmbils = MDetailAmbils;
	}

}
