package com.bridea.siak.model;

// default package
// Generated Jun 3, 2014 9:42:46 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * MDetailAmbil generated by hbm2java
 */
@Entity
@Table(name = "m_detail_ambil", catalog = "siak")
public class MDetailAmbil implements java.io.Serializable {

	private Integer daIdDetailAmbil;
	private MMahasiswa MMahasiswa;
	private MAmbil MAmbil;

	public MDetailAmbil() {
	}

	public MDetailAmbil(MMahasiswa MMahasiswa, MAmbil MAmbil) {
		this.MMahasiswa = MMahasiswa;
		this.MAmbil = MAmbil;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "da_id_detail_ambil", unique = true, nullable = false)
	public Integer getDaIdDetailAmbil() {
		return this.daIdDetailAmbil;
	}

	public void setDaIdDetailAmbil(Integer daIdDetailAmbil) {
		this.daIdDetailAmbil = daIdDetailAmbil;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "da_npm", nullable = false)
	public MMahasiswa getMMahasiswa() {
		return this.MMahasiswa;
	}

	public void setMMahasiswa(MMahasiswa MMahasiswa) {
		this.MMahasiswa = MMahasiswa;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "da_id_ambil", nullable = false)
	public MAmbil getMAmbil() {
		return this.MAmbil;
	}

	public void setMAmbil(MAmbil MAmbil) {
		this.MAmbil = MAmbil;
	}

}
