package com.bridea.siak.model;

// default package
// Generated Jun 3, 2014 10:26:47 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * MKomponenNilai generated by hbm2java
 */
@Entity
@Table(name = "m_komponen_nilai", catalog = "siak")
public class MKomponenNilai implements java.io.Serializable {

	private int knIdKomponenNilai;
	private byte knNilaiKehadiran;
	private long knNilaiTugas;
	private long knNilaiUts;
	private long knNilaiUas;
	private Set<MAmbil> MAmbils = new HashSet<MAmbil>(0);

	public MKomponenNilai() {
	}

	public MKomponenNilai(int knIdKomponenNilai, byte knNilaiKehadiran,
			long knNilaiTugas, long knNilaiUts, long knNilaiUas) {
		this.knIdKomponenNilai = knIdKomponenNilai;
		this.knNilaiKehadiran = knNilaiKehadiran;
		this.knNilaiTugas = knNilaiTugas;
		this.knNilaiUts = knNilaiUts;
		this.knNilaiUas = knNilaiUas;
	}

	public MKomponenNilai(int knIdKomponenNilai, byte knNilaiKehadiran,
			long knNilaiTugas, long knNilaiUts, long knNilaiUas,
			Set<MAmbil> MAmbils) {
		this.knIdKomponenNilai = knIdKomponenNilai;
		this.knNilaiKehadiran = knNilaiKehadiran;
		this.knNilaiTugas = knNilaiTugas;
		this.knNilaiUts = knNilaiUts;
		this.knNilaiUas = knNilaiUas;
		this.MAmbils = MAmbils;
	}

	@Id
	@Column(name = "kn_id_komponen_nilai", unique = true, nullable = false)
	public int getKnIdKomponenNilai() {
		return this.knIdKomponenNilai;
	}

	public void setKnIdKomponenNilai(int knIdKomponenNilai) {
		this.knIdKomponenNilai = knIdKomponenNilai;
	}

	@Column(name = "kn_nilai_kehadiran", nullable = false)
	public byte getKnNilaiKehadiran() {
		return this.knNilaiKehadiran;
	}

	public void setKnNilaiKehadiran(byte knNilaiKehadiran) {
		this.knNilaiKehadiran = knNilaiKehadiran;
	}

	@Column(name = "kn_nilai_tugas", nullable = false, precision = 10, scale = 0)
	public long getKnNilaiTugas() {
		return this.knNilaiTugas;
	}

	public void setKnNilaiTugas(long knNilaiTugas) {
		this.knNilaiTugas = knNilaiTugas;
	}

	@Column(name = "kn_nilai_uts", nullable = false, precision = 10, scale = 0)
	public long getKnNilaiUts() {
		return this.knNilaiUts;
	}

	public void setKnNilaiUts(long knNilaiUts) {
		this.knNilaiUts = knNilaiUts;
	}

	@Column(name = "kn_nilai_uas", nullable = false, precision = 10, scale = 0)
	public long getKnNilaiUas() {
		return this.knNilaiUas;
	}

	public void setKnNilaiUas(long knNilaiUas) {
		this.knNilaiUas = knNilaiUas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "MKomponenNilai")
	public Set<MAmbil> getMAmbils() {
		return this.MAmbils;
	}

	public void setMAmbils(Set<MAmbil> MAmbils) {
		this.MAmbils = MAmbils;
	}

}
