package com.bridea.siak.model;

// default package
// Generated Jun 9, 2014 10:29:45 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * MMataKuliah generated by hbm2java
 */
@Entity
@Table(name = "m_mata_kuliah", catalog = "siak")
public class MMataKuliah implements java.io.Serializable {

	private String mkKodeMk;
	private String mkNamaMk;
	private byte mkSks;
	private byte mkSemester;
	private boolean mkStatus;
	private Set<MAmbil> MAmbils = new HashSet<MAmbil>(0);

	public MMataKuliah() {
	}

	public MMataKuliah(String mkKodeMk, String mkNamaMk, byte mkSks,
			byte mkSemester, boolean mkStatus) {
		this.mkKodeMk = mkKodeMk;
		this.mkNamaMk = mkNamaMk;
		this.mkSks = mkSks;
		this.mkSemester = mkSemester;
		this.mkStatus = mkStatus;
	}

	public MMataKuliah(String mkKodeMk, String mkNamaMk, byte mkSks,
			byte mkSemester, boolean mkStatus, Set<MAmbil> MAmbils) {
		this.mkKodeMk = mkKodeMk;
		this.mkNamaMk = mkNamaMk;
		this.mkSks = mkSks;
		this.mkSemester = mkSemester;
		this.mkStatus = mkStatus;
		this.MAmbils = MAmbils;
	}

	@Id
	@Column(name = "mk_kode_mk", unique = true, nullable = false, length = 8)
	public String getMkKodeMk() {
		return this.mkKodeMk;
	}

	public void setMkKodeMk(String mkKodeMk) {
		this.mkKodeMk = mkKodeMk;
	}

	@Column(name = "mk_nama_mk", nullable = false, length = 60)
	public String getMkNamaMk() {
		return this.mkNamaMk;
	}

	public void setMkNamaMk(String mkNamaMk) {
		this.mkNamaMk = mkNamaMk;
	}

	@Column(name = "mk_sks", nullable = false)
	public byte getMkSks() {
		return this.mkSks;
	}

	public void setMkSks(byte mkSks) {
		this.mkSks = mkSks;
	}

	@Column(name = "mk_semester", nullable = false)
	public byte getMkSemester() {
		return this.mkSemester;
	}

	public void setMkSemester(byte mkSemester) {
		this.mkSemester = mkSemester;
	}

	@Column(name = "mk_status", nullable = false)
	public boolean isMkStatus() {
		return this.mkStatus;
	}

	public void setMkStatus(boolean mkStatus) {
		this.mkStatus = mkStatus;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "MMataKuliah")
	public Set<MAmbil> getMAmbils() {
		return this.MAmbils;
	}

	public void setMAmbils(Set<MAmbil> MAmbils) {
		this.MAmbils = MAmbils;
	}

}
